### ISSUE TITLE
Scan has no results 

### ISSUE THREAD

**Issue by Avamander** [routerkeygen/routerkeygenAndroid#27] opened 2015-10-10 13:05 UTC
Device: LG D605 CM11 (by Varcain)

Even though settings (Settings->WiFi) show available networks, routerkeygen sees no networks at all.

**Comment by ruiaraujo** [comment] 2015-10-10 20:00
That's probably a bug on your ROM. Do other Wifi related apps able to scan Wifi?

**Comment by Avamander** [comment] 2015-10-10 21:42
Other apps work perfectly. My phone's ROM is almost unmodified cm11, but nothing WiFi related was modified.

**Comment by ruiaraujo** [comment] 2015-10-10 22:03
That's very odd. Can you try uninstalling and getting the latest version of RK in the Play Store?

I can't replicate it at all.

**Comment by ruiaraujo** [comment] 2015-11-07 18:50
Have you disabled any permissions using something like AppOps?

**Comment by bmaeser** [comment] 2015-11-17 17:30
i have the same issue on a google nexus 5, vendor os (android 6.0, build mra58n) not rooted or anything.

reinstall via app-store does not solve issue. when i download the apt manually and try to install it, i get "could not be installed", but no more information than that.

**Comment by ruiaraujo** [comment] 2015-11-17 17:32
Look at the app permissions. Wifi scanning requires location on 6.0.

**Comment by bmaeser** [comment] 2015-11-17 17:34
permissions are all on. including location.

**Comment by ruiaraujo** [comment] 2015-11-17 18:59
That's odd because I am using a Nexus 5 as a test device.

I will try to reproduce. Try disabling/enabling the permissions

**Comment by bmaeser** [comment] 2015-11-23 15:31
ok this solved the issue:
- disable all permissions
- reboot
- enable all permissions
- reboot

very odd

**Comment by RealEnder** [comment] 2016-04-27 17:24
Just turn on location and it will work.
See here: https://code.google.com/p/android/issues/detail?id=185370

**Comment by Avamander** [comment] 2016-04-27 18:06
I can't do that because google messed up Google Play Services so that if I
enable location it starts crashing.

**Comment by ruiaraujo** [comment] 2017-11-05 23:38
Should be fixed with the latest release.

**Closed by ruiaraujo** 2017-11-05 23:38 UTC
